{% set python_min = python_min|default("3.9") %}
{% set name = "hdpws" %}
{% set version = "0.6.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hdpws-{{ version }}.tar.gz
  sha256: 32d4dcbfb15f7cd50b030cbbd6c6bb9d49d4d839b2e0a3094fe3be58e5b247fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >={{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}.*
    - python-dateutil >=2.8.0
    - requests >=2.20
    - urllib3 >=1.26.14

test:
  imports:
    - hdpws
  commands:
    - pip check
  requires:
    - python >={{ python_min }}.*
    - pip

about:
  home: https://heliophysicsdata.gsfc.nasa.gov/WebServices
  summary: NASA's Heliophysics Data Portal Web Service Client Library
  license: NOSL
  license_file: NASA_Open_Source_Agreement_1.3.txt
  description: |
    This library provides a simple python interface to
    NASA's [Heliophysics Data Portal's](https://heliophysicsdata.gsfc.nasa.gov/)
    (HDP) Space Physics Archive, Search, and Extract
    ([SPASE](https://spase-group.org/)) Web Service.  This library implements
    the client side of the
    [HDP RESTful web services](https://heliophysicsdata.gsfc.nasa.gov/WebServices/).
    For more general details about the HDP web services, see
    https://heliophysicsdata.gsfc.nasa.gov/WebServices/.
    ![SPASE Inside](https://spase-group.org/assets/images/spase-inside.png)

extra:
  recipe-maintainers:
    - FreddyCruz
    - FCMCoding
    - candeynasa
    - ericthewizard
    - berniegsfc
