{% set name = "hdpws" %}
{% set version = "0.6.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hdpws-{{ version }}.tar.gz
  sha256: c90e68b53a88210a096d3e741318c09eb576eb09703ab73deda6db85b1c68299

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil >=2.8.0
    - requests >=2.20
    - urllib3 >=1.26.14

test:
  imports:
    - hdpws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://heliophysicsdata.gsfc.nasa.gov/WebServices
  summary: NASA's Heliophysics Data Portal Web Service Client Library
  license: NASA-1.3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - candeynasa
    - ericthewizard
    - berniegsfc
